CREATE TABLE public.transactionhistory (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	userid varchar NULL,
	operation varchar NULL,
	"comment" varchar NULL,
	amount integer NULL,
	datetime timestamp with time zone NULL,
	CONSTRAINT transactionhistory_pk PRIMARY KEY (id)
);
